# Generated by Django 4.2.14 on 2024-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='options',
            field=models.BooleanField(blank=True, choices=[(0, 'Finger Food'), (1, 'Snacks'), (2, 'Craft Beer'), (3, 'Soda')], null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='session_type',
            field=models.IntegerField(choices=[(0, 'Action Movies'), (1, 'Comedy Movies'), (2, 'Drama Movies'), (3, 'Video Games')], default='3'),
        ),
        migrations.AddField(
            model_name='book',
            name='wishes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Wishes & Information'),
        ),
    ]
