# Generated by Django 4.2.14 on 2024-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_book_booker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='options',
            field=models.IntegerField(blank=True, choices=[(0, 'Finger Food'), (1, 'Snacks'), (2, 'Craft Beer'), (3, 'Soda')], null=True),
        ),
    ]
