# Generated by Django 4.2.14 on 2024-07-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_book_options_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Options',
        ),
    ]
