# Generated by Django 4.2.14 on 2024-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_delete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='options',
            field=models.CharField(choices=[(0, 'Finger Food'), (1, 'Snacks'), (2, 'Craft Beer'), (3, 'Soda')], default=0),
            preserve_default=False,
        ),
    ]
